"""empty message

Revision ID: bd3d29e4df7e
Revises: ec75c4f02c93
Create Date: 2025-10-09 09:35:37.165565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3d29e4df7e'
down_revision: Union[str, Sequence[str], None] = 'ec75c4f02c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'address',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_constraint(op.f('phone_numbers_organization_id_fkey'), 'phone_numbers', type_='foreignkey')
    op.create_foreign_key(None, 'phone_numbers', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone_numbers', type_='foreignkey')
    op.create_foreign_key(op.f('phone_numbers_organization_id_fkey'), 'phone_numbers', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.alter_column('buildings', 'address',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
